- job: delete
  index:
    - "elastalert_status*"
  save: 7

- job: delete
  index:
    - "access*"
  save: 31

- job: backup
  type: s3
  index:
    - "access-{today_one}"
    - "mcafee_audit_{today_two}"
    - "system_secure_{today_two}"
  body:
    # index为特殊变量, 自动循环替换
    indices: "{index}"
    include_global_state: False
