- job: delete
  index:
    # nginx日志保留30天
    - "logstash-nginx_access_*"
  save: 30

- job: backup
  type: s3
  index:
    - "system_history_{yesterday_two}"
    - "mysql_audit-{yesterday_two}"
    - ".kibana"
  body:
    # index为特殊变量, 自动循环替换
    indices: "{index}"
    include_global_state: False